; generated by PrusaSlicer 2.9.4
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S210 ; set nozzle temp
M109 S210 ; wait for nozzle temp
G28 ; home all axis
G1 Z0.28 F240
G92 E0
G1 X2 Y140 E10 F1500 ; prime line
M107
